name: Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install websockets opencv-python mediapipe
          npm install -g wscat

      - name: Start HTTP server
        run: |
          nohup python -m http.server 8080 &
          echo "HTTP server started at http://localhost:8080"

      - name: Run WebSocket server
        run: |
          docker run --device=/dev/video0:/dev/video0 -v $(pwd):/app python:3.9 bash -c "pip install -r /app/requirements.txt && python /app/app.py"
          npx wscat -c ws://localhost:8089 || echo "WebSocket connection failed"
          sleep 60m
