name: Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install websockets opencv-python mediapipe

      - name: Start HTTP server
        run: |
          nohup python -m http.server 8080 &
          echo "HTTP server started at http://localhost:8080"

      - name: Run WebSocket server
        run: |
          nohup python app.py &
          echo "WebSocket server started at ws://localhost:8089"
          sleep 60m
